const initState = {
  books: [
    {
      id: 1,
      title: "مقدمة ابن خلدون ",
      author: "ابن خلدون ",
      isbn: "1289499030",
      delete: false,
    },
    {
      id: 2,
      title: "الحاوي في الطب ",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 3,
      title: "ابو البصل ",
      author: "  محمد رزاز ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 4,
      title: "الطب  في الحاوي ",
      author: " الرازي ابو بكر  ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 5,
      title: "في الحاوي في الطب ",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 6,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 7,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 8,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 9,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 10,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 11,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 12,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 13,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 14,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 15,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 16,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 17,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 18,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 19,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 20,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 21,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 22,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 23,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 24,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
    {
      id: 25,
      title: " الحاوي في الطب في الحاوي",
      author: "ابو بكر الرازي ",
      isbn: "893847239479",
      delete: false,
    },
  ],
};
export default initState;
